name: base_project_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_gen_runner: 5.3.1
  intl: any
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  flutter_smart_dialog: ^4.9.6+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^4.2.1
  jiffy: ^6.2.0

  # Networking
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.0.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

dependency_overrides:
  flutter_gen_core: 5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/

flutter_intl:
  enabled: true
  arb_dir: lib/gen/l10n
  output_dir: lib/gen/l10n/generated
  main_locale: en

flutter_gen:
  output: lib/gen/assets
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
